apiVersion: v1
kind: Secret
metadata:
  name: {{ include "domain-manager.fullname" . }}-admin
  labels:
    {{- include "domain-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.admin.password | quote }}
  admin-email: {{ .Values.admin.email | quote }}
