apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domain-manager-data
  namespace: domain-manager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vultr-block-storage
